### ISSUE TITLE
Why TOEFL

### ISSUE THREAD

**Issue by niananto** [Mushtari-Sadia/TOEFL-prep#1]
Hi, could you please elaborate the purpose of you taking the TOEFL? What institutions require it?

**Comment by Mushtari-Sadia** [comment]
Almost all universities in US, Canada, UK and Australia require an English proficiency test score (TOEFL/ IELTS). Some people take IELTS, some people take TOEFL. I've heard people say that IELTS is better for canadian universities but I'm not sure about this fact.

I've also heard that TOEFL is preferred in US and IELTS is preferred in Europe. Some US institutions only accept TOEFL score, which is why I chose TOEFL over IELTS. But I didn't fact check this, and the universities I've looked at till now accept both.
